# Generated by Django 4.2.5 on 2023-09-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%d/%m/%Y')),
                ('timeframe', models.CharField(choices=[('1min', '1min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('1H', '1H'), ('4H', '4H'), ('1D', '1D')], max_length=5)),
                ('ex_mov_average', models.IntegerField(blank=True)),
            ],
        ),
    ]
