# Generated by Django 4.2.5 on 2023-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='ex_mov_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
