# Generated by Django 4.2.5 on 2023-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0002_alter_uploadfiles_ex_mov_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='timeframe',
            field=models.CharField(choices=[('1min', '1min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('1H', '1H'), ('4H', '4H'), ('D', '1D')], max_length=5),
        ),
    ]
